# Form implementation generated from reading ui file 'Playfair.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(643, 498)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 70, 47, 13))
        self.label.setObjectName("label")
        self.txt_plaintext = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.txt_plaintext.setGeometry(QtCore.QRect(80, 50, 271, 81))
        self.txt_plaintext.setObjectName("txt_plaintext")
        self.txt_key = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_key.setGeometry(QtCore.QRect(80, 160, 271, 20))
        self.txt_key.setObjectName("txt_key")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 47, 13))
        self.label_2.setObjectName("label_2")
        self.btn_encrypt = QtWidgets.QPushButton(parent=Dialog)
        self.btn_encrypt.setGeometry(QtCore.QRect(80, 410, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(parent=Dialog)
        self.btn_decrypt.setGeometry(QtCore.QRect(210, 410, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_clear = QtWidgets.QPushButton(parent=Dialog)
        self.btn_clear.setGeometry(QtCore.QRect(350, 410, 75, 23))
        self.btn_clear.setObjectName("btn_clear")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 300, 47, 13))
        self.label_4.setObjectName("label_4")
        self.txt_encrypt = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.txt_encrypt.setGeometry(QtCore.QRect(80, 200, 271, 71))
        self.txt_encrypt.setObjectName("txt_encrypt")
        self.txt_decrypt = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.txt_decrypt.setGeometry(QtCore.QRect(80, 290, 271, 71))
        self.txt_decrypt.setObjectName("txt_decrypt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Plaintext:"))
        self.label_2.setText(_translate("Dialog", "Key:"))
        self.btn_encrypt.setText(_translate("Dialog", "Encrypt"))
        self.btn_decrypt.setText(_translate("Dialog", "Decrypt"))
        self.btn_clear.setText(_translate("Dialog", "Clear"))
        self.label_3.setText(_translate("Dialog", "Encrypt"))
        self.label_4.setText(_translate("Dialog", "decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
