# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] = "../platforms"
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(837, 370)
        self.btn_encrypt = QtWidgets.QPushButton(Dialog)
        self.btn_encrypt.setGeometry(QtCore.QRect(80, 270, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.txt_plaintext = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_plaintext.setGeometry(QtCore.QRect(80, 40, 301, 91))
        self.txt_plaintext.setObjectName("txt_plaintext")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(330, 10, 171, 16))
        self.label_2.setObjectName("label_2")
        self.txt_ciphertext = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_ciphertext.setGeometry(QtCore.QRect(80, 150, 301, 91))
        self.txt_ciphertext.setObjectName("txt_ciphertext")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 61, 16))
        self.label_3.setObjectName("label_3")
        self.txt_information = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_information.setGeometry(QtCore.QRect(510, 40, 301, 91))
        self.txt_information.setObjectName("txt_information")
        self.txt_signature = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_signature.setGeometry(QtCore.QRect(510, 150, 301, 91))
        self.txt_signature.setObjectName("txt_signature")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(440, 40, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(450, 150, 51, 20))
        self.label_5.setObjectName("label_5")
        self.btn_decrypt = QtWidgets.QPushButton(Dialog)
        self.btn_decrypt.setGeometry(QtCore.QRect(280, 270, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(Dialog)
        self.btn_sign.setGeometry(QtCore.QRect(530, 270, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(Dialog)
        self.btn_verify.setGeometry(QtCore.QRect(710, 270, 75, 23))
        self.btn_verify.setObjectName("btn_verify")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_encrypt.setText(_translate("Dialog", "Encrypt"))
        self.label.setText(_translate("Dialog", "Plain text"))
        self.label_2.setText(_translate("Dialog", "RSA Cipher"))
        self.label_3.setText(_translate("Dialog", "Cipher text"))
        self.label_4.setText(_translate("Dialog", "information"))
        self.label_5.setText(_translate("Dialog", "Signature"))
        self.btn_decrypt.setText(_translate("Dialog", "Decrypt"))
        self.btn_sign.setText(_translate("Dialog", "Sign"))
        self.btn_verify.setText(_translate("Dialog", "verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
